name: bipul_cli
description: A powerful yet simple CLI for generating Flutter projects with clean architecture.
version: 0.1.0
homepage: https://github.com/Syed-Bipul-Rahman/bipul_cli
author: Syed Bipul Rahman <info@syedbbipul.me>

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  args: ^2.4.0
  path: ^1.8.3
  recase: ^4.0.0
  mustache_template: ^2.0.0
  ansicolor:
  logging: ^1.2.0

dev_dependencies:
  test: any

executables:
  bipul: main