name: bipul_cli
description: A powerful yet simple CLI for generating Flutter projects and features with a clean, scalable architecture following DRY and SOLID principles.
version: 0.1.1
homepage: https://github.com/Syed-Bipul-Rahman/bipul_cli
repository: https://github.com/Syed-Bipul-Rahman/bipul_cli
issue_tracker: https://github.com/Syed-Bipul-Rahman/bipul_cli/issues
# maintainers:
#   - name: Syed Bipul Rahman
#     email: info@syedbbipul.me

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  args: ^2.4.0
  path: ^1.8.3
  recase: ^4.0.0
  mustache_template: ^2.0.0
  ansicolor: ^2.0.1
  logging: ^1.2.0
  process:

dev_dependencies:
  test: ^1.24.0
  lints: ^2.0.0

executables:
  bipul: main